// Code generated by mockery. DO NOT EDIT.

package servicehttp

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// mockHttpClient is an autogenerated mock type for the httpClient type
type mockHttpClient struct {
	mock.Mock
}

type mockHttpClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockHttpClient) EXPECT() *mockHttpClient_Expecter {
	return &mockHttpClient_Expecter{mock: &_m.Mock}
}

// Do provides a mock function with given fields: req
func (_m *mockHttpClient) Do(req *http.Request) (*http.Response, error) {
	ret := _m.Called(req)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(*http.Request) *http.Response); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockHttpClient_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type mockHttpClient_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - req *http.Request
func (_e *mockHttpClient_Expecter) Do(req interface{}) *mockHttpClient_Do_Call {
	return &mockHttpClient_Do_Call{Call: _e.mock.On("Do", req)}
}

func (_c *mockHttpClient_Do_Call) Run(run func(req *http.Request)) *mockHttpClient_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*http.Request))
	})
	return _c
}

func (_c *mockHttpClient_Do_Call) Return(_a0 *http.Response, _a1 error) *mockHttpClient_Do_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTnewMockHttpClient interface {
	mock.TestingT
	Cleanup(func())
}

// newMockHttpClient creates a new instance of mockHttpClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockHttpClient(t mockConstructorTestingTnewMockHttpClient) *mockHttpClient {
	mock := &mockHttpClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
