name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          check-latest: true
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.51
          skip-pkg-cache: true
          skip-build-cache: true
          args: --timeout=10m

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      flipt:
        image: ghcr.io/flipt-io/openfeature-testbed:latest
        ports:
          - 8080:8080

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          check-latest: true
          cache: true

      - name: Run tests
        run: go test -v -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
